### ISSUE TITLE
Which version of C — c89? c99?

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-c#2]
Hi!

Is this project using c89 or c99? It would be great to document it and maybe also to add compile flags that make sure that there are no regressions regarding that choice, e.g. `-std=c89 -pedantic`. At least in case of c89. What do you think?

Best, Sebastian

**Comment by mity** [comment]
I'm quite confident it is c99-compliant (or at least very close to, maybe some hairsplitter may find some problematic details), and generally, the code is quite conservative and old-school because I am not a youngster anymore.

About c89, strictly speaking, I have no idea and someone would have to review the code carefully: Even though I see myself as experienced in C, there were actually only few and limited cases in my career when I really used floating point math and I am not really sure whether all the math functions used in `hsluv.c` are guaranteed by the c89 standard.

Additionally, enabling c89 might be problematic because `acutest.h`, the header-only test suite used, is certainly **not** c89-compatible. It uses for example `snprintf()` which I believe was not available in c89 even though more or less all platforms provided `snprintf()` in early 90s, long before the c99 standard was actually born. (Except maybe Microsoft's C runtime which provides `_snprintf()`.) 

(This one fact is strong enough for me to not care about c89 compatibility much. It is three decades old and I tend to see any standard without so widely used and needed function as the `snprintf()` simply as a dead one.)

From a pragmatic point of view: If you encounter a platform/compiler where it does not compile with a reasonable set of options, feel free to open an issue or (preferably) a pull request. Fixing it should generally be quite simple.

I can imagine the only platforms we might have problem to support might be some embedded ones, which may lack any support for the `double` type and/or `double` math functions or which may have that support only emulated and hence very slow. (To be usable on such platforms, it might need complete rewrite of the code and use some magic in integer-only arithmetic. But that would be a completely new project and my motivation to work on that is zero.)

**Comment by mity** [comment]
At least on my machine, gcc 8.1 is completely happy with `-std=c99 -pedantic`.

**Comment by hartwork** [comment]
Thanks for your quick reply!
I wanted to see it for myself now and tried compiling with `-std=c89 -pedantic`. The code is not c89, neither the tests nor the library. Totally fine with me, but also interesting to know.
I'll add label `c99` to the project now.

**Comment by hartwork** [comment]
Should we change the main project description like this?:
```diff
--- C implementation of HSLuv (revision 4)
+++ C99 implementation of HSLuv (revision 4)
```
?

**Comment by hartwork** [comment]
Thanks for 3d357f265adaf5d4722d7a43474add5aa8928079

**Comment by mity** [comment]
> Should we change the main project description?

Given how old C89 is, I see C and C99 more or less as synonyms but feel free to do it if you see it as an important thing.

**Comment by hartwork** [comment]
Okay done. Thank you!

**Comment by RoyiAvital** [comment]
Any chance to create versions to this repository?

**Comment by mity** [comment]
You mean to manage C89 and C99? I don't want to maintain C89.

**Comment by hartwork** [comment]
My guess is @RoyiAvital means releases and Git tags. @RoyiAvital please elaborate, ideally in a new ticket in case it's not strictly related to c89 vs c99. Thank you!

**Comment by RoyiAvital** [comment]
Sorry, I searched for Version.
Yes, I mean tagging a commit so there will be official versions.

Like tagging the current code as `1.0.000` and then update.

**Comment by mity** [comment]
Ok. Created a new issue for it and locking it here.
